name: Build and Push MERN Docker Images to GHCR (initialization purposes only)

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually from the GitHub UI

jobs:
  build-and-push-init:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push images to GHCR

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 3: Convert repository owner to lowercase (docker image names must all be lowercase)
      - name: Set repository owner lowercase
        id: owner_lowercase
        run: echo "owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 4: Build the React app
      - name: Install and Build React App
        run: |
          cd react/mern-todo-list
          npm ci # Install dependencies (prefer ci for CI environments)
          npm run build # Build the React app
          cd ../../ # Return to home directory
          
      # Step 5: Build and Push React Docker Image
      - name: Build and Push React App Image
        run: |
          docker build -t ghcr.io/${{ env.owner_lowercase }}/mern-react-todo:v0.0.1 react/mern-todo-list
          docker push ghcr.io/${{ env.owner_lowercase }}/mern-react-todo:v0.0.1
      # Step 6: Build and Push Express Docker Image
      - name: Build and Push Express App Image
        run: |
          docker build -t ghcr.io/${{ env.owner_lowercase }}/mern-express-todo:v0.0.1 express
          docker push ghcr.io/${{ env.owner_lowercase }}/mern-express-todo:v0.0.1
      # Step 7: Build and Push Mongo Docker Image
      - name: Build and Push Mongo Image
        run: |
          docker build -t ghcr.io/${{ env.owner_lowercase }}/mern-mongo-todo:v0.0.1 mongoDB
          docker push ghcr.io/${{ env.owner_lowercase }}/mern-mongo-todo:v0.0.1
